### PR TITLE
add fortran interoperability

### PR DESCRIPTION
**Pull request by germasch**
This is basd on kokkos, essentially using their way of passing Fortran arrays (including non-contiguous ones). Adapted to create `gtensor_span` on the C++ side.

### CODE REVIEW

**Comment by bd4** [comment]
This looks great!

**Comment by germasch** [comment]
The CI doesn't look like it's setup for Fortran (some images don't seem to have a Fortran compiler), but there's at least one case in there where the Fortran code gets compiled, so that's better than nothing.

There's also no real tests, just something that should probably better be moved into examples, and of course it wouldn't hurt
to add some actual tests, too.

**Comment by germasch** [comment]
Not sure that I've got all the cmake subtleties right, but it looks like this works with gtensor as a subdir or via find_package if the consuming project is using cmake.

I haven't tried to make this work with regular make -- probably will have to add `-I...include/gtensor/fortran` to the Fortran command line, and link the right (`fgtensor`) library.

**Review by bd4 — APPROVED** [review]
LGTM. Regarding unit tests, I would prefer not adding pFUnit as a dependency to CI and general testing, I've had serious issues getting it to work on different machines. Eventually, maybe we can do something custom, even if it's just running some fortran exes and ensuring the return code is 0.

**Comment by germasch** [comment]
I agree, I wouldn't want to pull in pfunit. I think it's actually pretty straight forward to convert my "example" into a test that checks rather than prints the passed array. I've just been too lazy ;)

**Pull request merged**
