### PR TITLE
fix debug builds

### PR DESCRIPTION
**Pull request by bd4**

### CODE REVIEW

**Review by germasch — APPROVED** [review]
Seems like a good idea to add debug build to the CI ;)

I'm usually also using assert in the same fashion. However, I think it'd be better to have those checks happen unconditionally -- they are cheap compared to the actual operation, and if they trigger, they may not trigger because of a bug internal to gtensor, but rather because of someone using the API wrong, and it'd be much easier to let them know even in production mode.

**Comment by bd4** [comment]
That is a good point - I guess we need to define our own gt::assert for this, for unconditional asserts not affect by NDEBUG?

**Comment by germasch** [comment]
There is `Expects`, not standard yet I believe. I think this may be what we want. Or we could just throw exceptions, but it's a bit lengthy to have those all over the place.

**Comment by bd4** [comment]
Looks like Microsoft GSL has a standalone header we could drop in: https://github.com/microsoft/GSL/blob/main/include/gsl/assert

**Comment by germasch** [comment]
Yeah, looks like that should work (in particular if it's usable standalone, I haven't checked)

**Pull request merged**
