### PR TITLE
use official cmake support for sycl and hip backends

### PR DESCRIPTION
**Pull request by bd4**

### CODE REVIEW

**Comment by bd4** [comment]
Downside of this is that the SYCL cmake support requires cmake 3.23

**Review by germasch — APPROVED** [review]
This is definitely something I've been thinking we should do for quite a while ;)

**Comment by bd4** [comment]
This break building GENE on Intel unfortunately, MKL related link error. So some more work will be required.

**Comment by bd4** [comment]
The ROCm build does seem to work at least.

**Comment by bd4** [comment]
On Intel systems / oneAPI versions where GENE fails to link, gtensor examples and benchmarks link and run just fine. Something about the GENE cmake is messing up the link chain, and it is not linking libmkl_sycl.

**Comment by bd4** [comment]
Issue building GENE was because of options form included custom FindMKL.cmake conflicting with MKLConfig.cmake. Not too hard to workaround.

**Pull request merged**
