### PR TITLE
Pr/bench stencil tmp

### PR DESCRIPTION
**Pull request by bd4**

### CODE REVIEW

**Review by germasch — COMMENTED** [review]
Other than combining some unrelated changes in a single PR, looks good to me. I think doing multi-d stencils with arbitrary coefficient arrays is going to be more complicated still, but this definitely works for the benchmark.

**Comment by bd4** [comment]
The unrelated changes is github being difficult when I try to stage a series of commits and seemingly not updating the diffs when I try to rebase or when the base changes, i.e. when the earlier PRs are merged. If you look at the diff view tab, it should show the real diff.

**Comment by bd4** [comment]
hm I guess the diff tab also shows it. I guess I have to stage multiple PRs a different way. I'll rebase and force push

**Comment by bd4** [comment]
Cleaned up, I believe is ready for merge now.

**Review by germasch — APPROVED** [review]
👍

**Pull request merged**
